### PR TITLE
Update ExoPlayer to 2.19.1 (Xamarin branch)

### PR DESCRIPTION
**Pull request by ArchangelWTF**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Updates the Xamarin branch to 2.19.1

This also heavily breaks ExoPlayer.Effect, but I'm not even sure if that's largely used in XF anyway.

@martijn00 Not sure if you saw my previous comment on the other PR as you had asked me to look into the dependabot PR's, if you could set me as a collaborator of this repository so that I can re-run and merge if needed that'd be great!

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines 
- [ ] Relevant documentation was updated
- [ ] Rebased onto current develop

### CODE REVIEW

**Review by martijn00 — APPROVED** [review]

**Comment by martijn00** [comment]
@ArchangelWTF i've given you Triage access, can you see if that works for you? I'm happy to keep merging and maintaining stuff with your help.

**Comment by martijn00** [comment]
@ArchangelWTF and please look carefully when updating dependencies if they match the Exoplayer versions used here: https://github.com/google/ExoPlayer/blob/release-v2/constants.gradle#L46

**Comment by ArchangelWTF** [comment]
> @ArchangelWTF i've given you Triage access, can you see if that works for you? I'm happy to keep merging and maintaining stuff with your help.

@martijn00  I think I may need write permissions to approve GitHub PR's and to re-run CI/CD through GitHub actions, I can close them but that's not much help.

I definitively intend even with write to still have you approve and merge my PR's at least to make sure I've got a final go-ahead (For production branches at least) and I think write will be handy to have regardless due to me being able to move the work I've done already on Media3 here instead of on my fork.

**Comment by ArchangelWTF** [comment]
@martijn00 Did you have a chance to look at the comment I've written above yet?

**Pull request merged**
