### PR TITLE
Added FLAC extension

### PR DESCRIPTION
**Pull request by hig-dev**
This adds the FLAC extension.

### CODE REVIEW

**Comment by martijn00** [comment]
I've thought about bringing this in too, the problem is that this isn't published on bintray or anything so every update i need to compile it myself first. That makes it a bit hard. It would be good if Google would add this themselves first.

**Comment by hig-dev** [comment]
Yes that's a pity. There is a discussion about that at https://github.com/google/ExoPlayer/issues/1434
I had to compile the FLAC extension with the Android NDK myself because I needed it for my project.

**Comment by cncb-gh** [comment]
Is this going to be added?  Or can you tell my how I can get a compiled version of the flac extension and add it to my project manually?  Thanks.

**Comment by hig-dev** [comment]
@cncb-gh You can compile the fork at https://github.com/hig-dev/ExoPlayerXamarin

**Comment by martijn00** [comment]
I've updated the whole repo structure. Maybe we can work this out with: https://github.com/PaulWoitaschek/ExoPlayer-Extensions

**Pull request closed without merging**
