### PR TITLE
Media3

### PR DESCRIPTION
**Pull request by ArchangelWTF**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)
Introduces Media3 (Fixes: https://github.com/Baseflow/ExoPlayerXamarin/issues/157)

@martijn00 This fully introduces Media3, I've updated the PackageId's as I think it would break to have media3 published on the current ExoPlayer Id's..

As well as that, if you merge this.. Could you set media3 as the main branch for this repository? This will allow us to keep the current develop and exoplayer branches should we need to do anything with them.

### :thinking: Checklist before submitting

- [ ] All projects build
- [ ] Follows style guide lines 
- [ ] Relevant documentation was updated
- [ ] Rebased onto current develop

### CODE REVIEW

**Comment by ArchangelWTF** [comment]
@martijn00 When you have time to look this over can you approve and merge this?

**Comment by Mackly** [comment]
Hi! Is there a reason why this has not been integrated and released to the nuget package ?

**Comment by ArchangelWTF** [comment]
@Mackly Because it was decided not to be adopted, also Xamarin will have a Media3 package available soon (Went into review this week: https://github.com/xamarin/AndroidX/issues/710)

**Comment by Mackly** [comment]
Thanks for the reply, I am following closely

**Pull request closed without merging**
