### PR TITLE
Update to 1.5.2 and port of demo project

### PR DESCRIPTION
**Pull request by MKuckert**
I ported the [ExoPlayer demo application](https://github.com/google/ExoPlayer/tree/master/demo) to C#

### CODE REVIEW

**Comment by martijn00** [comment]
Looks good to me! Huge thanks for helping on this! Is it ready to merge?

**Comment by MKuckert** [comment]
I'm adding some stuff. Pushing some more in some minutes.

**Comment by MKuckert** [comment]
Now it's ready to go :)

**Comment by martijn00** [comment]
Thanks again! I'll try to push an update soon.

**Pull request merged**
